### ISSUE TITLE
[C][Linux][GCC 4.4.4] Another (new) typedef redefinition

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#637]
Hi,

Recently #466 has been corrected thanks for that. Since then  new typdef redefinition shows up.
I'm on develop
Here is the patch for that.

```
From 76bd41322e7bdc874ba0a1b3ee1fe9d04b91b9a4 Mon Sep 17 00:00:00 2001
Date: Fri, 17 Jun 2016 09:25:10 +0200
Subject: [PATCH 1/1] Enable GCC 4.4 compilation

---
 c/iothub_client/inc/iothub_client_ll.h    | 4 ++--
 c/iothub_client/inc/iothub_transport_ll.h | 4 ++--
 2 files changed, 4 insertions(+), 4 deletions(-)

diff --git a/c/iothub_client/inc/iothub_client_ll.h b/c/iothub_client/inc/iothub_client_ll.h
index 6411729..7d50d6b 100644
--- a/c/iothub_client/inc/iothub_client_ll.h
+++ b/c/iothub_client/inc/iothub_client_ll.h
@@ -144,11 +144,11 @@ extern "C"
 	} IOTHUB_CLIENT_DEVICE_CONFIG;
 
 	/** @brief	This struct captures IoTHub transport configuration. */
-	typedef struct IOTHUBTRANSPORT_CONFIG_TAG
+	struct IOTHUBTRANSPORT_CONFIG_TAG
 	{
 		const IOTHUB_CLIENT_CONFIG* upperConfig;
 		PDLIST_ENTRY waitingToSend;
-	}IOTHUBTRANSPORT_CONFIG;
+	};
 
 
 	/**
diff --git a/c/iothub_client/inc/iothub_transport_ll.h b/c/iothub_client/inc/iothub_transport_ll.h
index b83d55f..41d9fdb 100644
--- a/c/iothub_client/inc/iothub_transport_ll.h
+++ b/c/iothub_client/inc/iothub_transport_ll.h
@@ -55,10 +55,10 @@ pfIoTHubTransport_Unsubscribe IoTHubTransport_Unsubscribe;   \
 pfIoTHubTransport_DoWork IoTHubTransport_DoWork;             \
 pfIoTHubTransport_GetSendStatus IoTHubTransport_GetSendStatus  /*there's an intentional missing ; on this line*/ \
 
-	typedef struct TRANSPORT_PROVIDER_TAG
+	struct TRANSPORT_PROVIDER_TAG
 	{
 		TRANSPORT_PROVIDER_FIELDS;
-	}TRANSPORT_PROVIDER;
+	};
 
 #ifdef __cplusplus
 }
-- 
2.8.2
```

**Comment by anhashia** [comment]
Looking into the issue

**Comment by anhashia** [comment]
Hi @lmussier 
As you also noted this is coming because current code is tested with **gcc version 4.9 or higher**. Redefinition of typedef is not supported in older gcc compiler 4.4 that you are using. I assume that you **don't** have an option to move to gcc 4.9 or higher and want code to build with gcc 4.4. I am looking at the best way to resolve this issue including looking at your proposed changes..

**Comment by lmussier** [comment]
You are right, and since a similar "bug" has been corrected before, I point you the issue to keep the older gcc compliance (and maybe some IAR compatibility : see https://github.com/Azure/azure-iot-sdks/issues/466#issuecomment-221538547).

Thanks.

**Comment by anhashia** [comment]
Hi @lmussier 
I am looking at it to see the best way to resolve this compilation error with **older** gcc 4.4 compiler. I looked at the patch mentioned by you in the comment section.  Can you provide more details on what changes you are proposing to make it compatible with older gcc 4.4 compiler which doesn't support **re-definition** ?

**Comment by lmussier** [comment]
Hi @anhashia 
The main reason that make the code incompatible with gcc 4.4 is the constructs of this type.

`typedef struct IOTHUBTRANSPORT_CONFIG_TAG IOTHUBTRANSPORT_CONFIG;`

And duplicate the typedef for the same type elsewhere.

```
	typedef struct IOTHUBTRANSPORT_CONFIG_TAG
	{
		const IOTHUB_CLIENT_CONFIG* upperConfig;
		PDLIST_ENTRY waitingToSend;
	}IOTHUBTRANSPORT_CONFIG;
```
It's not valid with gcc < 4.5 we are not allowed to refined a typdedef for the same type.

**Comment by anhashia** [comment]
Yeah, looking into this

**Comment by anhashia** [comment]
Investigating this.

**Comment by anhashia** [comment]
Fix is in develop branch https://github.com/Azure/azure-iot-sdks/commit/7d4ac20f13d7fca1edeb61de17672b810ce36028

**Comment by anhashia** [comment]
Fix is in develop branch  7d4ac20. Closing the issue. Please let us know if you're still having issues. Thanks.
