### ISSUE TITLE
[C][Linux][GCC 4.4.4] Compile error : redefinition of typedef 'AGENT_DATA_TYPE'

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#466]
Hi,

This [issue](https://github.com/Azure/azure-iot-sdks/issues/302) is still opened, at least, for the AGENT_DATA_TYPE part.

```
/home/lmussier/workspace/Agents/iothub/agent/external/azure-iot-sdks/c/serializer/inc/agenttypesystem.h:643: error: redefinition of typedef 'AGENT_DATA_TYPE'
/home/lmussier/workspace/Agents/iothub/agent/external/azure-iot-sdks/c/serializer/inc/agenttypesystem.h:33: note: previous declaration of 'AGENT_DATA_TYPE' was here
```

 I'm cross compiling using GCC 4.4.4. The possibility to have a redefinition of typedef has been introduced in [gcc 4.5](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/ChangeLog;h=da66a2873a415b200a60ad25dc710594e0534362;hb=ce3765bf44e49ef0568a1ad4a0b7f807591d6412) if I'm not wrong.

**Comment by markrad** [comment]
Hi. I reviewed the GCC documentation that you were kind enough to link in your comments. I believe you are right regarding the issue being caused by that particular construct not being supported by GCC prior to 4.5. 
However, though you will likely be able to make minor modifications to the header to enable it to work with your 4.4.4 version of GCC, at this time we will not be incorporating such a change. If you review the page here https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md#linux you will notice that it specifically calls out for GCC version 4.9 or higher. Fortunately most build issues can be circumvented to enable compilation with early versions of GCC. 

Mark Radbourne (MSFT)

**Comment by lmussier** [comment]
Oh, it seems I've missed the 4.9 requirement.
Would you mind let this issue open until it's corrected, or the 4.9 requirement is set in stone, and previous version of GCC won't be supported at all?

**Comment by markrad** [comment]
Having discussed this further, If this is the only issue that prevents GCC 4.4 being used then we will consider modifying the code and dropping the minimum version to GCC 4.4. I will keep you updated.

_Mark Radbourne (MSFT)_

**Comment by jjlee3** [comment]
Warning[Pe301]: typedef name has already been declared (with same type) C:\Code\azure-iot-sdks\c\serializer\inc\agenttypesystem.h 643 

I got a similar problem under IAR Embedded Workbench IDE - ARM 7.60.1.

**Comment by markrad** [comment]
This issue has been fixed in the develop branch. It should be merged into master on July 6.

_Mark Radbourne MSFT_

**Comment by lmussier** [comment]
@markrad This issue is also present in the dmpreview branch. Do you correct the issue globally ?

**Comment by damonbarry** [comment]
We merge develop into dmpreview on a regular basis (once every week or two).  So this change will naturally make its way into dmpreview.  Thanks!

**Comment by lmussier** [comment]
@damonbarry Sorry I misspoke, the issue I'm talking about is redefining typedef, not this particular one. The develop branch wasn't compile due to typedef redefinitions, it has been corrected (and broken again cf. #637 ) My question was, do you have automated build jobs to check this constructs, (which is incompatible with gcc < 4.4 and maybe with IAR) ?
